"""Stable vocabularies for provider-neutral data-access contracts."""

from enum import StrEnum


class ProviderCapability(StrEnum):
    SECURITY_REFERENCE = "SECURITY_REFERENCE"
    DAILY_PRICES = "DAILY_PRICES"
    CORPORATE_ACTIONS = "CORPORATE_ACTIONS"
    FINANCIAL_FACTS = "FINANCIAL_FACTS"
    FILING_METADATA = "FILING_METADATA"
    DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD"


class DataCategory(StrEnum):
    DAILY_PRICES = "DAILY_PRICES"
    CORPORATE_ACTIONS = "CORPORATE_ACTIONS"
    FINANCIAL_FACTS = "FINANCIAL_FACTS"
    FILING_METADATA = "FILING_METADATA"
    SOURCE_DOCUMENTS = "SOURCE_DOCUMENTS"


class QualityStatus(StrEnum):
    PASS = "PASS"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAIL = "FAIL"


class ProviderStatus(StrEnum):
    APPROVED = "APPROVED"
    APPROVED_FOR_PERSONAL_RESEARCH_ONLY = "APPROVED_FOR_PERSONAL_RESEARCH_ONLY"
    NEEDS_CREDENTIALS = "NEEDS_CREDENTIALS"
    NEEDS_LICENSE_CONFIRMATION = "NEEDS_LICENSE_CONFIRMATION"
    EXPERIMENTAL = "EXPERIMENTAL"
    NOT_ALLOWED = "NOT_ALLOWED"


class DataOrigin(StrEnum):
    FIXTURE = "FIXTURE"
    LIVE = "LIVE"


class AccessMode(StrEnum):
    OFFLINE = "OFFLINE"
    ONLINE = "ONLINE"


class LiveStatus(StrEnum):
    NOT_LIVE = "NOT_LIVE"
    LIVE = "LIVE"
