"""Closed vocabularies for verifiable research reports."""

from enum import StrEnum


class ReportType(StrEnum):
    DATA_QUALITY_REPORT = "DATA_QUALITY_REPORT"
    EVIDENCE_SUMMARY = "EVIDENCE_SUMMARY"
    FINANCIAL_RESEARCH_DRAFT = "FINANCIAL_RESEARCH_DRAFT"
    FULL_RESEARCH_DRAFT = "FULL_RESEARCH_DRAFT"


class ReportLocale(StrEnum):
    ZH_CN = "zh-CN"
    EN_US = "en-US"


class ReportSection(StrEnum):
    RESEARCH_SCOPE = "RESEARCH_SCOPE"
    SECURITY_IDENTITY = "SECURITY_IDENTITY"
    DATA_AVAILABILITY = "DATA_AVAILABILITY"
    FINANCIAL_HEALTH = "FINANCIAL_HEALTH"
    VALUATION_SNAPSHOT = "VALUATION_SNAPSHOT"
    DOCUMENT_EVIDENCE = "DOCUMENT_EVIDENCE"
    CATALYST_EVIDENCE = "CATALYST_EVIDENCE"
    RISK_EVIDENCE = "RISK_EVIDENCE"
    CORPORATE_ACTIONS = "CORPORATE_ACTIONS"
    DATA_QUALITY = "DATA_QUALITY"
    CONFLICTS = "CONFLICTS"
    UNSUPPORTED_CLAIMS = "UNSUPPORTED_CLAIMS"
    LIMITATIONS = "LIMITATIONS"
    CLAIM_INDEX = "CLAIM_INDEX"
    EVIDENCE_APPENDIX = "EVIDENCE_APPENDIX"
    CITATION_APPENDIX = "CITATION_APPENDIX"
