"""create production data providers

Revision ID: 0008_production_providers
Revises: 0007_verifiable_reports
Create Date: 2026-07-29 22:05:19.298057
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008_production_providers"
down_revision: str | Sequence[str] | None = "0007_verifiable_reports"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_guards() -> None:
    op.execute(
        """
        CREATE FUNCTION stage9_reject_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'STAGE9_IMMUTABLE_RECORD';
        END;
        $$;
        """
    )
    for table in (
        "provider_raw_artifacts",
        "provider_ingestion_manifests",
        "provider_health_snapshots",
        "provider_audit_events",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION stage9_reject_mutation();
            """
        )
    op.execute(
        """
        CREATE FUNCTION stage9_guard_sync_run() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE
            terminal text[] := ARRAY[
                'COMPLETED','PARTIAL','BLOCKED','FAILED','CANCELLED'
            ];
        BEGIN
            IF TG_OP = 'DELETE' OR OLD.status = ANY(terminal) THEN
                RAISE EXCEPTION 'STAGE9_SYNC_RUN_IMMUTABLE';
            END IF;
            IF OLD.status <> NEW.status AND NOT (
                (OLD.status = 'PLANNED'
                    AND NEW.status = ANY(ARRAY['QUEUED','BLOCKED','CANCELLED']))
                OR (OLD.status = 'QUEUED'
                    AND NEW.status = ANY(ARRAY['RUNNING','BLOCKED','CANCELLED']))
                OR (OLD.status = 'RUNNING'
                    AND NEW.status = ANY(
                        ARRAY[
                            'PAUSED','COMPLETED','PARTIAL','BLOCKED',
                            'FAILED','CANCELLED'
                        ]
                    ))
                OR (OLD.status = 'PAUSED'
                    AND NEW.status = ANY(
                        ARRAY['QUEUED','RUNNING','BLOCKED','CANCELLED']
                    ))
            ) THEN
                RAISE EXCEPTION 'STAGE9_SYNC_RUN_TRANSITION_FORBIDDEN';
            END IF;
            RETURN NEW;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_provider_sync_runs_lifecycle
        BEFORE UPDATE OR DELETE ON provider_sync_runs
        FOR EACH ROW EXECUTE FUNCTION stage9_guard_sync_run();
        """
    )
    op.execute(
        """
        CREATE FUNCTION stage9_guard_checkpoint_revision() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'STAGE9_CHECKPOINT_DELETE_FORBIDDEN';
            END IF;
            IF NEW.revision <> OLD.revision + 1
               OR NEW.provider_definition_id <> OLD.provider_definition_id
               OR NEW.provider_capability_id <> OLD.provider_capability_id
               OR NEW.scope_checksum <> OLD.scope_checksum
               OR NEW.id <> OLD.id
               OR NEW.created_at <> OLD.created_at THEN
                RAISE EXCEPTION 'STAGE9_CHECKPOINT_REVISION_FORBIDDEN';
            END IF;
            RETURN NEW;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_provider_sync_checkpoints_revision
        BEFORE UPDATE OR DELETE ON provider_sync_checkpoints
        FOR EACH ROW EXECUTE FUNCTION stage9_guard_checkpoint_revision();
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_definitions",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("definition_version", sa.String(length=32), nullable=False),
        sa.Column("adapter_version", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("data_domain", sa.String(length=64), nullable=False),
        sa.Column("definition_status", sa.String(length=16), nullable=False),
        sa.Column("production_status", sa.String(length=16), nullable=False),
        sa.Column("official_domains", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("license_policy_version", sa.String(length=32), nullable=False),
        sa.Column("credential_reference_id", sa.Uuid(), nullable=True),
        sa.Column("source_register_version", sa.String(length=32), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_definitions_checksum"),
        sa.CheckConstraint("code ~ '^[A-Z][A-Z0-9_]{2,63}$'", name="ck_provider_definitions_code"),
        sa.CheckConstraint(
            "definition_status IN "
            "('DRAFT','ACTIVE','SUSPENDED','RETIRED','BLOCKED') "
            "AND production_status IN "
            "('ENABLED','CONDITIONAL','BLOCKED','TEST_ONLY')",
            name="ck_provider_definitions_status",
        ),
        sa.ForeignKeyConstraint(
            ["credential_reference_id"],
            ["provider_credential_references.id"],
            name="fk_provider_definitions_credential_reference",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_definitions"),
        sa.UniqueConstraint("code", "definition_version", name="uq_provider_definitions_identity"),
    )
    op.create_index(
        "ix_provider_definitions_code_status",
        "provider_definitions",
        ["code", "definition_status"],
        unique=False,
    )
    op.create_table(
        "provider_capabilities",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("capability_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("data_domain", sa.String(length=64), nullable=False),
        sa.Column("market_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("security_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("operations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_capabilities_checksum"),
        sa.CheckConstraint("code ~ '^[A-Z][A-Z0-9_]{2,63}$'", name="ck_provider_capabilities_code"),
        sa.CheckConstraint(
            "status IN ('IMPLEMENTED_OFFLINE','ENABLED','BLOCKED','RETIRED')",
            name="ck_provider_capabilities_status",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_capabilities_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_capabilities"),
        sa.UniqueConstraint(
            "provider_definition_id",
            "code",
            "capability_version",
            name="uq_provider_capabilities_identity",
        ),
    )
    op.create_index(
        "ix_provider_capabilities_lookup",
        "provider_capabilities",
        ["provider_definition_id", "code", "status"],
        unique=False,
    )
    op.create_table(
        "provider_credential_references",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("reference_version", sa.String(length=32), nullable=False),
        sa.Column("resolver_kind", sa.String(length=16), nullable=False),
        sa.Column("declared_name", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("safe_label", sa.String(length=128), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(resolver_kind = 'NONE' AND declared_name IS NULL "
            "AND status = 'NOT_REQUIRED') OR "
            "(resolver_kind = 'ENVIRONMENT' AND declared_name IS NOT NULL "
            "AND declared_name ~ '^[A-Z][A-Z0-9_]{2,63}$' "
            "AND status <> 'NOT_REQUIRED')",
            name="ck_provider_credential_references_resolver",
        ),
        sa.CheckConstraint(
            "checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_credential_references_checksum"
        ),
        sa.CheckConstraint(
            "status IN ('NOT_REQUIRED','NOT_READ','CONFIGURED_METADATA_ONLY','MISSING','BLOCKED')",
            name="ck_provider_credential_references_status",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_credential_references_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_credential_references"),
        sa.UniqueConstraint(
            "provider_definition_id",
            "reference_version",
            name="uq_provider_credential_references_identity",
        ),
    )
    op.create_index(
        "ix_provider_credential_references_provider",
        "provider_credential_references",
        ["provider_definition_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_provider_definitions_credential_reference",
        "provider_definitions",
        "provider_credential_references",
        ["credential_reference_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "provider_health_snapshots",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("configuration_status", sa.String(length=32), nullable=False),
        sa.Column("credential_status", sa.String(length=32), nullable=False),
        sa.Column("license_status", sa.String(length=32), nullable=False),
        sa.Column("live_validation_status", sa.String(length=32), nullable=False),
        sa.Column("limiting_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_health_snapshots_checksum"
        ),
        sa.CheckConstraint(
            "status IN ('READY','CONDITIONAL','BLOCKED') "
            "AND configuration_status IN ('VALID','INVALID','BLOCKED') "
            "AND credential_status IN "
            "('NOT_REQUIRED','NOT_READ','CONFIGURED_METADATA_ONLY','MISSING','BLOCKED') "
            "AND license_status IN "
            "('APPROVED','RESTRICTED_REVIEW_REQUIRED','BLOCKED','UNKNOWN_REQUIRES_REVIEW') "
            "AND live_validation_status IN "
            "('NOT_ATTEMPTED','RUNNING','PASSED','FAILED','BLOCKED','CANCELLED')",
            name="ck_provider_health_snapshots_states",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_health_snapshots_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_health_snapshots"),
    )
    op.create_index(
        "ix_provider_health_snapshots_provider_time",
        "provider_health_snapshots",
        ["provider_definition_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "provider_license_policies",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("acquisition", sa.String(length=32), nullable=False),
        sa.Column("raw_storage", sa.String(length=32), nullable=False),
        sa.Column("cache", sa.String(length=32), nullable=False),
        sa.Column("derived_use", sa.String(length=32), nullable=False),
        sa.Column("redistribution", sa.String(length=32), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("deletion_required", sa.Boolean(), nullable=False),
        sa.Column("attribution_required", sa.Boolean(), nullable=False),
        sa.Column("terms_source_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition IN "
            "('ALLOWED','PROHIBITED','UNKNOWN_REQUIRES_REVIEW','NOT_APPLICABLE') "
            "AND raw_storage IN "
            "('ALLOWED','PROHIBITED','UNKNOWN_REQUIRES_REVIEW','NOT_APPLICABLE') "
            "AND cache IN "
            "('ALLOWED','PROHIBITED','UNKNOWN_REQUIRES_REVIEW','NOT_APPLICABLE') "
            "AND derived_use IN "
            "('ALLOWED','PROHIBITED','UNKNOWN_REQUIRES_REVIEW','NOT_APPLICABLE') "
            "AND redistribution IN "
            "('ALLOWED','PROHIBITED','UNKNOWN_REQUIRES_REVIEW','NOT_APPLICABLE')",
            name="ck_provider_license_policies_permissions",
        ),
        sa.CheckConstraint(
            "checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_license_policies_checksum"
        ),
        sa.CheckConstraint(
            "status IN "
            "('APPROVED','RESTRICTED_REVIEW_REQUIRED','BLOCKED',"
            "'UNKNOWN_REQUIRES_REVIEW')",
            name="ck_provider_license_policies_status",
        ),
        sa.CheckConstraint(
            "(retention_days IS NULL OR retention_days BETWEEN 1 AND 36500) "
            "AND (expires_at IS NULL OR expires_at > reviewed_at)",
            name="ck_provider_license_policies_window",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_license_policies_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_license_policies"),
        sa.UniqueConstraint(
            "provider_definition_id", "policy_version", name="uq_provider_license_policies_identity"
        ),
    )
    op.create_index(
        "ix_provider_license_policies_lookup",
        "provider_license_policies",
        ["provider_definition_id", "policy_version"],
        unique=False,
    )
    op.create_table(
        "provider_policies",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("endpoint_policy_version", sa.String(length=32), nullable=False),
        sa.Column("network_enabled", sa.Boolean(), nullable=False),
        sa.Column("max_requests", sa.Integer(), nullable=False),
        sa.Column("max_response_bytes", sa.Integer(), nullable=False),
        sa.Column("max_total_bytes", sa.Integer(), nullable=False),
        sa.Column("max_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("max_redirects", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_second", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("retry_base_delay_seconds", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cache_enabled", sa.Boolean(), nullable=False),
        sa.Column("cache_ttl_seconds", sa.Integer(), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_policies_checksum"),
        sa.CheckConstraint(
            "max_requests BETWEEN 1 AND 10000 "
            "AND max_response_bytes BETWEEN 1 AND 52428800 "
            "AND max_total_bytes >= max_response_bytes "
            "AND max_total_bytes <= 10737418240 "
            "AND max_duration_seconds BETWEEN 1 AND 86400 "
            "AND max_attempts BETWEEN 1 AND 3 "
            "AND max_redirects BETWEEN 0 AND 5 "
            "AND rate_limit_per_second > 0 "
            "AND retry_base_delay_seconds > 0 "
            "AND ((cache_enabled AND cache_ttl_seconds BETWEEN 1 AND 86400) "
            "OR (NOT cache_enabled AND cache_ttl_seconds IS NULL)) "
            "AND (retention_days IS NULL OR retention_days BETWEEN 1 AND 36500)",
            name="ck_provider_policies_limits",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_policies_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_policies"),
        sa.UniqueConstraint(
            "provider_definition_id", "policy_version", name="uq_provider_policies_identity"
        ),
    )
    op.create_index(
        "ix_provider_policies_lookup",
        "provider_policies",
        ["provider_definition_id", "policy_version"],
        unique=False,
    )
    op.create_table(
        "provider_circuit_breakers",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("half_open_probe_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('CLOSED','OPEN','HALF_OPEN') AND failure_count >= 0",
            name="ck_provider_circuit_breakers_state",
        ),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_circuit_breakers_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_circuit_breakers_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_circuit_breakers"),
        sa.UniqueConstraint(
            "provider_definition_id",
            "provider_capability_id",
            name="uq_provider_circuit_breakers_scope",
        ),
    )
    op.create_index(
        "ix_provider_circuit_breakers_lookup",
        "provider_circuit_breakers",
        ["provider_definition_id", "provider_capability_id", "status"],
        unique=False,
    )
    op.create_table(
        "provider_freshness_policies",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("market_code", sa.String(length=32), nullable=False),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("expected_delay_seconds", sa.Integer(), nullable=False),
        sa.Column("unknown_published_at_status", sa.String(length=16), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_delay_seconds >= 0 "
            "AND unknown_published_at_status IN ('PARTIAL','BLOCKED') "
            "AND checksum ~ '^[0-9a-f]{64}$'",
            name="ck_provider_freshness_policies_bounds",
        ),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_freshness_policies_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_freshness_policies_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_freshness_policies"),
        sa.UniqueConstraint(
            "provider_definition_id",
            "provider_capability_id",
            "market_code",
            "policy_version",
            name="uq_provider_freshness_policies_identity",
        ),
    )
    op.create_index(
        "ix_provider_freshness_policies_lookup",
        "provider_freshness_policies",
        ["provider_definition_id", "provider_capability_id", "market_code"],
        unique=False,
    )
    op.create_table(
        "provider_live_validation_runs",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("max_requests", sa.Integer(), nullable=False),
        sa.Column("max_bytes", sa.Integer(), nullable=False),
        sa.Column("consumed_requests", sa.Integer(), nullable=False),
        sa.Column("consumed_bytes", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('NOT_ATTEMPTED','AUTHORIZED','RUNNING','PASS','FAILED','BLOCKED')",
            name="ck_provider_live_validation_runs_status",
        ),
        sa.CheckConstraint(
            "max_requests BETWEEN 1 AND 100 "
            "AND max_bytes BETWEEN 1 AND 52428800 "
            "AND consumed_requests BETWEEN 0 AND max_requests "
            "AND consumed_bytes BETWEEN 0 AND max_bytes "
            "AND (completed_at IS NULL OR started_at IS NOT NULL) "
            "AND (started_at IS NULL OR expires_at > started_at)",
            name="ck_provider_live_validation_runs_budgets",
        ),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_live_validation_runs_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_live_validation_runs_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_live_validation_runs"),
    )
    op.create_index(
        "ix_provider_live_validation_runs_provider_time",
        "provider_live_validation_runs",
        ["provider_definition_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "provider_sync_checkpoints",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("scope_checksum", sa.String(length=64), nullable=False),
        sa.Column("watermark", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope_checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_sync_checkpoints_checksum"
        ),
        sa.CheckConstraint("revision >= 0", name="ck_provider_sync_checkpoints_revision"),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_sync_checkpoints_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_sync_checkpoints_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_sync_checkpoints"),
        sa.UniqueConstraint(
            "provider_definition_id",
            "provider_capability_id",
            "scope_checksum",
            name="uq_provider_sync_checkpoints_scope",
        ),
    )
    op.create_index(
        "ix_provider_sync_checkpoints_lookup",
        "provider_sync_checkpoints",
        ["provider_definition_id", "provider_capability_id", "scope_checksum"],
        unique=False,
    )
    op.create_table(
        "provider_sync_requests",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("license_policy_id", sa.Uuid(), nullable=False),
        sa.Column("credential_reference_id", sa.Uuid(), nullable=True),
        sa.Column("security_id", sa.Uuid(), nullable=True),
        sa.Column("universe_code", sa.String(length=64), nullable=True),
        sa.Column("research_as_of_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("range_start", sa.Date(), nullable=False),
        sa.Column("range_end", sa.Date(), nullable=False),
        sa.Column("execution_mode", sa.String(length=32), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_checksum", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "execution_mode IN ('OFFLINE','LIVE_VALIDATION')", name="ck_provider_sync_requests_mode"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(scope) = 'object' "
            "AND octet_length(scope::text) <= 65536 "
            "AND jsonb_typeof(budget) = 'object' "
            "AND octet_length(budget::text) <= 16384",
            name="ck_provider_sync_requests_json_bounds",
        ),
        sa.CheckConstraint(
            "request_checksum ~ '^[0-9a-f]{64}$' AND idempotency_key ~ '^[0-9a-f]{64}$'",
            name="ck_provider_sync_requests_checksums",
        ),
        sa.CheckConstraint(
            "range_start IS NOT NULL AND range_end IS NOT NULL AND range_end >= range_start",
            name="ck_provider_sync_requests_range",
        ),
        sa.ForeignKeyConstraint(
            ["credential_reference_id"],
            ["provider_credential_references.id"],
            name="fk_provider_sync_requests_credential",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["license_policy_id"],
            ["provider_license_policies.id"],
            name="fk_provider_sync_requests_license",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["provider_policies.id"],
            name="fk_provider_sync_requests_policy",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_sync_requests_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_sync_requests_definition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name="fk_provider_sync_requests_security",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_sync_requests"),
        sa.UniqueConstraint("idempotency_key", name="uq_provider_sync_requests_idempotency"),
    )
    op.create_index(
        "ix_provider_sync_requests_provider_created",
        "provider_sync_requests",
        ["provider_definition_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "provider_sync_plans",
        sa.Column("sync_request_id", sa.Uuid(), nullable=False),
        sa.Column("adapter_version", sa.String(length=32), nullable=False),
        sa.Column("checkpoint_revision", sa.Integer(), nullable=True),
        sa.Column("slices", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("slice_count", sa.Integer(), nullable=False),
        sa.Column("plan_checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(slices) = 'array' "
            "AND jsonb_array_length(slices) = slice_count "
            "AND octet_length(slices::text) <= 1048576",
            name="ck_provider_sync_plans_json_bound",
        ),
        sa.CheckConstraint(
            "plan_checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_sync_plans_checksum"
        ),
        sa.CheckConstraint(
            "slice_count BETWEEN 1 AND 10000", name="ck_provider_sync_plans_slice_count"
        ),
        sa.ForeignKeyConstraint(
            ["sync_request_id"],
            ["provider_sync_requests.id"],
            name="fk_provider_sync_plans_request",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_sync_plans"),
        sa.UniqueConstraint(
            "sync_request_id", "plan_checksum", name="uq_provider_sync_plans_identity"
        ),
    )
    op.create_index(
        "ix_provider_sync_plans_request", "provider_sync_plans", ["sync_request_id"], unique=False
    )
    op.create_table(
        "provider_sync_runs",
        sa.Column("sync_request_id", sa.Uuid(), nullable=False),
        sa.Column("sync_plan_id", sa.Uuid(), nullable=False),
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("consumed_requests", sa.Integer(), nullable=False),
        sa.Column("consumed_bytes", sa.Integer(), nullable=False),
        sa.Column("consumed_attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warning_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('COMPLETED','PARTIAL','BLOCKED','FAILED','CANCELLED') "
            "AND completed_at IS NOT NULL) OR "
            "(status NOT IN ('COMPLETED','PARTIAL','BLOCKED','FAILED','CANCELLED') "
            "AND completed_at IS NULL)",
            name="ck_provider_sync_runs_terminal_time",
        ),
        sa.CheckConstraint(
            "status IN "
            "('PLANNED','QUEUED','RUNNING','PAUSED','COMPLETED','PARTIAL',"
            "'BLOCKED','FAILED','CANCELLED')",
            name="ck_provider_sync_runs_status",
        ),
        sa.CheckConstraint(
            "consumed_requests >= 0 AND consumed_bytes >= 0 AND consumed_attempts >= 0",
            name="ck_provider_sync_runs_counters",
        ),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_sync_runs_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_sync_runs_definition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_plan_id"],
            ["provider_sync_plans.id"],
            name="fk_provider_sync_runs_plan",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_request_id"],
            ["provider_sync_requests.id"],
            name="fk_provider_sync_runs_request",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_sync_runs"),
        sa.UniqueConstraint(
            "sync_request_id", "sync_plan_id", name="uq_provider_sync_runs_identity"
        ),
    )
    op.create_index(
        "ix_provider_sync_runs_provider_status",
        "provider_sync_runs",
        ["provider_definition_id", "status"],
        unique=False,
    )
    op.create_table(
        "provider_audit_events",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("action_code", sa.String(length=128), nullable=False),
        sa.Column("decision_code", sa.String(length=128), nullable=False),
        sa.Column("safe_summary", sa.String(length=1024), nullable=False),
        sa.Column("event_checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_audit_events_checksum"
        ),
        sa.CheckConstraint(
            "length(actor_type) BETWEEN 1 AND 64 "
            "AND length(action_code) BETWEEN 1 AND 128 "
            "AND length(decision_code) BETWEEN 1 AND 128 "
            "AND length(safe_summary) BETWEEN 1 AND 1024",
            name="ck_provider_audit_events_safe",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_audit_events_definition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["provider_sync_runs.id"],
            name="fk_provider_audit_events_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_audit_events"),
    )
    op.create_index(
        "ix_provider_audit_events_provider_time",
        "provider_audit_events",
        ["provider_definition_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "provider_request_attempts",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("slice_id", sa.String(length=64), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("endpoint_id", sa.String(length=128), nullable=False),
        sa.Column("response_status_code", sa.Integer(), nullable=True),
        sa.Column("response_bytes", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("safe_error_code", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','BLOCKED','FAILED','CANCELLED')",
            name="ck_provider_request_attempts_status",
        ),
        sa.CheckConstraint(
            "attempt_number BETWEEN 1 AND 3 "
            "AND response_bytes >= 0 "
            "AND (response_status_code IS NULL "
            "OR response_status_code BETWEEN 100 AND 599)",
            name="ck_provider_request_attempts_bounds",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name="ck_provider_request_attempts_time",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["provider_sync_runs.id"],
            name="fk_provider_request_attempts_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_request_attempts"),
        sa.UniqueConstraint(
            "sync_run_id",
            "slice_id",
            "attempt_number",
            name="uq_provider_request_attempts_identity",
        ),
    )
    op.create_index(
        "ix_provider_request_attempts_run_order",
        "provider_request_attempts",
        ["sync_run_id", "slice_id", "attempt_number"],
        unique=False,
    )
    op.create_table(
        "provider_raw_artifacts",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("request_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("license_policy_id", sa.Uuid(), nullable=False),
        sa.Column("source_identity", sa.String(length=512), nullable=False),
        sa.Column("source_checksum", sa.String(length=64), nullable=False),
        sa.Column("byte_count", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("blob_key", sa.String(length=512), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synthetic_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(blob_key) BETWEEN 1 AND 512 AND blob_key !~ '(^/|^[A-Za-z]:|\\\\|\\.\\.)'",
            name="ck_provider_raw_artifacts_blob_key",
        ),
        sa.CheckConstraint(
            "source_checksum ~ '^[0-9a-f]{64}$'", name="ck_provider_raw_artifacts_checksum"
        ),
        sa.CheckConstraint(
            "synthetic_status IN "
            "('REAL_VERIFIED','FIXTURE_REAL_EXCERPT','SYNTHETIC_TEST_ONLY','UNKNOWN')",
            name="ck_provider_raw_artifacts_synthetic",
        ),
        sa.CheckConstraint("byte_count > 0", name="ck_provider_raw_artifacts_size"),
        sa.ForeignKeyConstraint(
            ["license_policy_id"],
            ["provider_license_policies.id"],
            name="fk_provider_raw_artifacts_license",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_raw_artifacts_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_raw_artifacts_definition",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_attempt_id"],
            ["provider_request_attempts.id"],
            name="fk_provider_raw_artifacts_attempt",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["provider_sync_runs.id"],
            name="fk_provider_raw_artifacts_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_raw_artifacts"),
        sa.UniqueConstraint(
            "provider_definition_id",
            "source_identity",
            "source_checksum",
            name="uq_provider_raw_artifacts_identity",
        ),
    )
    op.create_index(
        "ix_provider_raw_artifacts_source_checksum",
        "provider_raw_artifacts",
        ["provider_definition_id", "source_identity", "source_checksum"],
        unique=False,
    )
    op.create_table(
        "provider_cache_entries",
        sa.Column("provider_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_capability_id", sa.Uuid(), nullable=False),
        sa.Column("license_policy_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cache_key ~ '^[0-9a-f]{64}$'", name="ck_provider_cache_entries_key"),
        sa.CheckConstraint("expires_at > created_at", name="ck_provider_cache_entries_expiry"),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["provider_raw_artifacts.id"],
            name="fk_provider_cache_entries_artifact",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["license_policy_id"],
            ["provider_license_policies.id"],
            name="fk_provider_cache_entries_license",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_capability_id"],
            ["provider_capabilities.id"],
            name="fk_provider_cache_entries_capability",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_definition_id"],
            ["provider_definitions.id"],
            name="fk_provider_cache_entries_definition",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_cache_entries"),
        sa.UniqueConstraint(
            "provider_definition_id",
            "provider_capability_id",
            "license_policy_id",
            "cache_key",
            name="uq_provider_cache_entries_key",
        ),
    )
    op.create_index(
        "ix_provider_cache_entries_expiry",
        "provider_cache_entries",
        ["provider_definition_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "provider_ingestion_manifests",
        sa.Column("raw_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("adapter_version", sa.String(length=32), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("batch_checksum", sa.String(length=64), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warning_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("synthetic_status", sa.String(length=32), nullable=False),
        sa.Column("manifest_checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "batch_checksum ~ '^[0-9a-f]{64}$' AND manifest_checksum ~ '^[0-9a-f]{64}$'",
            name="ck_provider_ingestion_manifests_checksums",
        ),
        sa.CheckConstraint(
            "synthetic_status IN "
            "('REAL_VERIFIED','FIXTURE_REAL_EXCERPT','SYNTHETIC_TEST_ONLY','UNKNOWN')",
            name="ck_provider_ingestion_manifests_synthetic",
        ),
        sa.CheckConstraint("record_count >= 0", name="ck_provider_ingestion_manifests_count"),
        sa.ForeignKeyConstraint(
            ["raw_artifact_id"],
            ["provider_raw_artifacts.id"],
            name="fk_provider_ingestion_manifests_artifact",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["provider_sync_runs.id"],
            name="fk_provider_ingestion_manifests_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_ingestion_manifests"),
        sa.UniqueConstraint(
            "raw_artifact_id",
            "adapter_version",
            "parser_version",
            "schema_version",
            "manifest_checksum",
            name="uq_provider_ingestion_manifests_identity",
        ),
    )
    op.create_index(
        "ix_provider_ingestion_manifests_run",
        "provider_ingestion_manifests",
        ["sync_run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "provider_data_quality_issues",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_id", sa.Uuid(), nullable=False),
        sa.Column("rule_code", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("safe_detail", sa.String(length=1024), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('CRITICAL','HIGH','MEDIUM','LOW') "
            "AND status IN ('OPEN','RESOLVED','ACCEPTED')",
            name="ck_provider_data_quality_issues_state",
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["provider_ingestion_manifests.id"],
            name="fk_provider_data_quality_issues_manifest",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["provider_sync_runs.id"],
            name="fk_provider_data_quality_issues_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_data_quality_issues"),
    )
    op.create_index(
        "ix_provider_data_quality_issues_run_status",
        "provider_data_quality_issues",
        ["sync_run_id", "status", "severity"],
        unique=False,
    )
    op.create_table(
        "provider_dead_letters",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_id", sa.Uuid(), nullable=False),
        sa.Column("source_identity", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("safe_error_code", sa.String(length=128), nullable=False),
        sa.Column("safe_detail", sa.String(length=1024), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','REPAIRED','DISMISSED')", name="ck_provider_dead_letters_status"
        ),
        sa.CheckConstraint(
            "length(source_identity) BETWEEN 1 AND 512 "
            "AND length(safe_error_code) BETWEEN 1 AND 128 "
            "AND length(safe_detail) BETWEEN 1 AND 1024",
            name="ck_provider_dead_letters_safe",
        ),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["provider_ingestion_manifests.id"],
            name="fk_provider_dead_letters_manifest",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["provider_sync_runs.id"],
            name="fk_provider_dead_letters_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_provider_dead_letters"),
    )
    op.create_index(
        "ix_provider_dead_letters_run_status",
        "provider_dead_letters",
        ["sync_run_id", "status", "created_at"],
        unique=False,
    )
    _create_guards()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS stage9_guard_checkpoint_revision() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS stage9_guard_sync_run() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS stage9_reject_mutation() CASCADE")
    op.drop_constraint(
        "fk_provider_definitions_credential_reference",
        "provider_definitions",
        type_="foreignkey",
    )
    op.drop_index("ix_provider_dead_letters_run_status", table_name="provider_dead_letters")
    op.drop_table("provider_dead_letters")
    op.drop_index(
        "ix_provider_data_quality_issues_run_status", table_name="provider_data_quality_issues"
    )
    op.drop_table("provider_data_quality_issues")
    op.drop_index("ix_provider_ingestion_manifests_run", table_name="provider_ingestion_manifests")
    op.drop_table("provider_ingestion_manifests")
    op.drop_index("ix_provider_cache_entries_expiry", table_name="provider_cache_entries")
    op.drop_table("provider_cache_entries")
    op.drop_index("ix_provider_raw_artifacts_source_checksum", table_name="provider_raw_artifacts")
    op.drop_table("provider_raw_artifacts")
    op.drop_index("ix_provider_request_attempts_run_order", table_name="provider_request_attempts")
    op.drop_table("provider_request_attempts")
    op.drop_index("ix_provider_audit_events_provider_time", table_name="provider_audit_events")
    op.drop_table("provider_audit_events")
    op.drop_index("ix_provider_sync_runs_provider_status", table_name="provider_sync_runs")
    op.drop_table("provider_sync_runs")
    op.drop_index("ix_provider_sync_plans_request", table_name="provider_sync_plans")
    op.drop_table("provider_sync_plans")
    op.drop_index("ix_provider_sync_requests_provider_created", table_name="provider_sync_requests")
    op.drop_table("provider_sync_requests")
    op.drop_index("ix_provider_sync_checkpoints_lookup", table_name="provider_sync_checkpoints")
    op.drop_table("provider_sync_checkpoints")
    op.drop_index(
        "ix_provider_live_validation_runs_provider_time", table_name="provider_live_validation_runs"
    )
    op.drop_table("provider_live_validation_runs")
    op.drop_index("ix_provider_freshness_policies_lookup", table_name="provider_freshness_policies")
    op.drop_table("provider_freshness_policies")
    op.drop_index("ix_provider_circuit_breakers_lookup", table_name="provider_circuit_breakers")
    op.drop_table("provider_circuit_breakers")
    op.drop_index("ix_provider_policies_lookup", table_name="provider_policies")
    op.drop_table("provider_policies")
    op.drop_index("ix_provider_license_policies_lookup", table_name="provider_license_policies")
    op.drop_table("provider_license_policies")
    op.drop_index(
        "ix_provider_health_snapshots_provider_time", table_name="provider_health_snapshots"
    )
    op.drop_table("provider_health_snapshots")
    op.drop_index(
        "ix_provider_credential_references_provider", table_name="provider_credential_references"
    )
    op.drop_table("provider_credential_references")
    op.drop_index("ix_provider_capabilities_lookup", table_name="provider_capabilities")
    op.drop_table("provider_capabilities")
    op.drop_index("ix_provider_definitions_code_status", table_name="provider_definitions")
    op.drop_table("provider_definitions")
    # ### end Alembic commands ###
