"""Closed vocabularies for controlled research orchestration."""

from enum import StrEnum


class ResearchType(StrEnum):
    COMPANY_OVERVIEW = "COMPANY_OVERVIEW"
    FINANCIAL_HEALTH = "FINANCIAL_HEALTH"
    VALUATION_SNAPSHOT = "VALUATION_SNAPSHOT"
    CATALYSTS_AND_RISKS = "CATALYSTS_AND_RISKS"
    DATA_QUALITY_REVIEW = "DATA_QUALITY_REVIEW"
    FULL_RESEARCH_PACKAGE = "FULL_RESEARCH_PACKAGE"


class ResearchSection(StrEnum):
    SECURITY_IDENTITY = "SECURITY_IDENTITY"
    DATA_AVAILABILITY = "DATA_AVAILABILITY"
    FINANCIAL_HEALTH = "FINANCIAL_HEALTH"
    VALUATION_SNAPSHOT = "VALUATION_SNAPSHOT"
    DOCUMENT_EVIDENCE = "DOCUMENT_EVIDENCE"
    CATALYST_EVIDENCE = "CATALYST_EVIDENCE"
    RISK_EVIDENCE = "RISK_EVIDENCE"
    CORPORATE_ACTIONS = "CORPORATE_ACTIONS"
    DATA_QUALITY = "DATA_QUALITY"
    LIMITATIONS = "LIMITATIONS"


class ResearchMode(StrEnum):
    REAL_RESEARCH = "REAL_RESEARCH"
    SYNTHETIC_TEST_ONLY = "SYNTHETIC_TEST_ONLY"


class ResearchRunStatus(StrEnum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ResearchStepStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    PASS = "PASS"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAIL = "FAIL"
    SKIPPED = "SKIPPED"


class ToolInvocationStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PASS = "PASS"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAIL = "FAIL"


class ResearchStepType(StrEnum):
    RESOLVE_SECURITY = "RESOLVE_SECURITY"
    LOAD_SNAPSHOT = "LOAD_SNAPSHOT"
    QUERY_STRUCTURED_DATA = "QUERY_STRUCTURED_DATA"
    QUERY_DOCUMENT_EVIDENCE = "QUERY_DOCUMENT_EVIDENCE"
    VALIDATE_EVIDENCE = "VALIDATE_EVIDENCE"
    BUILD_CLAIMS = "BUILD_CLAIMS"
    VALIDATE_CLAIMS = "VALIDATE_CLAIMS"
    ASSEMBLE_PACKAGE = "ASSEMBLE_PACKAGE"


class PlannerType(StrEnum):
    DETERMINISTIC_TEMPLATE = "DETERMINISTIC_TEMPLATE"
    SCRIPTED_TEST = "SCRIPTED_TEST"
    MODEL_PROVIDER = "MODEL_PROVIDER"


class ReasoningProviderType(StrEnum):
    DETERMINISTIC_RULES = "DETERMINISTIC_RULES"
    SCRIPTED_TEST = "SCRIPTED_TEST"
    MODEL_PROVIDER = "MODEL_PROVIDER"


class ProviderHealthStatus(StrEnum):
    READY = "READY"
    BLOCKED = "BLOCKED"
    TEST_ONLY = "TEST_ONLY"


class ObservationType(StrEnum):
    SECURITY_IDENTITY = "SECURITY_IDENTITY"
    STRUCTURED_METRIC = "STRUCTURED_METRIC"
    FINANCIAL_FACT = "FINANCIAL_FACT"
    DOCUMENT_EVIDENCE = "DOCUMENT_EVIDENCE"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    DATA_QUALITY = "DATA_QUALITY"
    TOOL_ERROR = "TOOL_ERROR"
    BLOCKED_CAPABILITY = "BLOCKED_CAPABILITY"


class ObservationStatus(StrEnum):
    PASS = "PASS"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAIL = "FAIL"


class EvidenceType(StrEnum):
    SECURITY_MASTER_EVIDENCE = "SECURITY_MASTER_EVIDENCE"
    SNAPSHOT_EVIDENCE = "SNAPSHOT_EVIDENCE"
    STRUCTURED_FACT_EVIDENCE = "STRUCTURED_FACT_EVIDENCE"
    DERIVED_METRIC_EVIDENCE = "DERIVED_METRIC_EVIDENCE"
    METRIC_LINEAGE_EVIDENCE = "METRIC_LINEAGE_EVIDENCE"
    DOCUMENT_CITATION_EVIDENCE = "DOCUMENT_CITATION_EVIDENCE"
    CORPORATE_ACTION_EVIDENCE = "CORPORATE_ACTION_EVIDENCE"
    DATA_QUALITY_EVIDENCE = "DATA_QUALITY_EVIDENCE"
    BLOCKED_CAPABILITY_EVIDENCE = "BLOCKED_CAPABILITY_EVIDENCE"


class EvidenceStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    FUTURE_DATA = "FUTURE_DATA"
    SOURCE_MISSING = "SOURCE_MISSING"
    CONFLICTING = "CONFLICTING"
    BLOCKED = "BLOCKED"


class SyntheticStatus(StrEnum):
    REAL_VERIFIED = "REAL_VERIFIED"
    FIXTURE_REAL_EXCERPT = "FIXTURE_REAL_EXCERPT"
    SYNTHETIC_TEST_ONLY = "SYNTHETIC_TEST_ONLY"
    UNKNOWN = "UNKNOWN"


class ClaimType(StrEnum):
    IDENTITY = "IDENTITY"
    FINANCIAL_FACT = "FINANCIAL_FACT"
    FINANCIAL_METRIC = "FINANCIAL_METRIC"
    VALUATION_METRIC = "VALUATION_METRIC"
    DOCUMENT_DISCLOSURE = "DOCUMENT_DISCLOSURE"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    DATA_QUALITY = "DATA_QUALITY"
    LIMITATION = "LIMITATION"


class ClaimSupportStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    CONFLICTING = "CONFLICTING"
    UNSUPPORTED = "UNSUPPORTED"
    BLOCKED = "BLOCKED"


class ClaimLifecycleStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class EvidenceRole(StrEnum):
    PRIMARY = "PRIMARY"
    CORROBORATING = "CORROBORATING"
    CONTRADICTING = "CONTRADICTING"
    CONTEXT = "CONTEXT"
    LIMITATION = "LIMITATION"


class ResearchPackageStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"


class PackageSectionStatus(StrEnum):
    PASS = "PASS"
    NOT_REQUESTED = "NOT_REQUESTED"
    NO_EVIDENCE = "NO_EVIDENCE"
    BLOCKED = "BLOCKED"
    PARTIAL = "PARTIAL"


class ResearchRunEventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    STATE_TRANSITION = "STATE_TRANSITION"
    PLAN_CREATED = "PLAN_CREATED"
    STEP_TRANSITION = "STEP_TRANSITION"
    TOOL_ATTEMPT = "TOOL_ATTEMPT"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    WARNING = "WARNING"
    RUN_TERMINATED = "RUN_TERMINATED"
